<?php
class Disques extends \_DefaultController {

	public function __construct(){
		parent::__construct();
		$this->title="Disques";
		$this->model="Disque";
	}
	public function frm($id = NULL)
	{
		$name="";
		if(array_key_exists("name",$_POST)) {
			$name = $_POST["name"];
		}
		$this->loadView("formulaire/creation_disque.html");
		#parent::frm($id); // TODO: Change the autogenerated stub
	}
}