<?php
class Disques extends \_DefaultController {

	public function __construct(){
		parent::__construct();
		$this->title="Disques";
		$this->model="Disque";
	}
	public function frm($id = NULL)
	{
		if (array_key_exists("id",$_POST)) {
			$name = $_POST["name"];
			$id = $_POST["id"];
			$user= $_POST["user"];
			$createdAt= $_POST["createdte"];
			$tarif= $_POST["tarif"];
		}
		$disque=new Disque();
		$disque=setId($id);
		$disque=setNom($name);
		$disque=setUtilisateur($user);
		$disque=setTarifs($tarif);
		$disque=setCreatedAte($createdAt);

		$this->loadView("formulaire/creation_disque.html", array("id"=> $id));
		#parent::frm($id); // TODO: Change the autogenerated stub
	}
}